#!/usr/bin/env python3
"""Export the chain's coefficients once, for Python and SystemVerilog both.

    ./.venv/bin/python model/export_coefficients.py

Writes three files from one computation:

  model/export/coefficients.json      canonical, and what Python reads
  hdl/rtl/lyrebird_coeffs_pkg.sv      generated package, what the RTL reads
  hdl/sim/coeffs/*.hex                $readmemh files for testbenches

Coefficients exist only as values computed at runtime otherwise. Two people
deriving them separately get answers that differ in the last bits and build
stages that do not compose, so they are derived once here and everything else
reads the result.

Every value is exported as an integer in its fixed-point representation, not
as a float. The integer is what the hardware holds; a float would have to be
converted again at every use, which is where the last-bit differences creep in.
"""

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from lyrebird_model import chain, halfband, modulator  # noqa: E402

ROOT = HERE.parent
# Per-stage coefficient widths from the fixed-point study in README.md,
# keyed by the stage index the cascade reports.
STAGE_BITS = {1: 26, 4: 22, 5: 19, 6: 18, 7: 10, 8: 8, 9: 8}
# Modulator coefficients are NOT a pure fraction: the last one exceeds 1.337,
# which a signed 24-bit fraction cannot hold. Two integer bits are allocated,
# so a coefficient is value * 2**MOD_FRAC in a signed MOD_BITS word.
MOD_BITS = 24
MOD_FRAC = 22          # Q2.22: sign, 1 integer bit, 22 fractional
SIGNAL_BITS = 28       # datapath signal word, from the same study


def q(value, bits, frac=None):
    """Signed fixed-point integer, with an overflow check.

    `frac` defaults to a pure fraction. Half-band taps never exceed 0.5, so
    that is right for them; the modulator's do exceed one and need integer
    bits, which is why this is explicit rather than assumed.
    """
    frac = bits - 1 if frac is None else frac
    out = int(round(value * (1 << frac)))
    lim = (1 << (bits - 1)) - 1
    if not -lim - 1 <= out <= lim:
        raise ValueError(
            f"{value} needs more than {bits} bits at Q{bits-1-frac}.{frac}: "
            f"{out} exceeds {lim}")
    return out


def main() -> int:
    cascade = halfband.build("48k")
    stages = []
    for st in cascade.distinct():
        bits = STAGE_BITS.get(st.index, 26)
        taps, ripple, stop = st.hb.quantized(bits)
        ints = [q(float(t), bits) for t in taps]
        stages.append({
            "index": st.index,
            "f_in_hz": st.f_in, "f_out_hz": st.f_out,
            "coeff_bits": bits,
            "n_taps": len(ints),
            "n_nonzero": int(sum(1 for v in ints if v)),
            "ripple_db": round(float(ripple), 6),
            "stopband_db": round(float(stop), 3),
            "taps": ints,
        })

    ntf = modulator.synthesize_ntf(3)
    data = {
        "generated_by": "model/export_coefficients.py",
        "note": "Integers are fixed-point; divide by 2^(bits-1) for the value.",
        "signal_bits": SIGNAL_BITS,
        "element_clock_hz": {k: v for k, v in chain.ELEMENT_CLOCK.items()},
        "quantizer": {"bits": chain.QUANT_BITS, "levels": chain.N_LEVELS,
                      "elements_per_side": chain.N_ELEMENTS},
        "modulator": {
            "order": len(ntf.a), "topology": "CIFB with input feedforward",
            # From run_modarith.py. Only the first integrator needs the wide
            # word: rounding there is integrated twice more before reaching
            # the quantizer, so it is amplified at low frequency.
            "state_bits": [28, 20, 20],
            "state_int_bits": 1,
            "state_frac_bits": [26, 18, 18],
            "coeff_bits": MOD_BITS,
            "coeff_frac_bits": MOD_FRAC,
            "a": [q(float(v), MOD_BITS, MOD_FRAC) for v in ntf.a],
        },
        "interpolation": {
            "stages_total": chain.N_STAGES,
            "stages_by_rate": {str(m.fs): m.n_stages for m in chain.modes("48k")},
            "distinct_stages": stages,
        },
    }

    out = HERE / "export"
    out.mkdir(exist_ok=True)
    data["note"] = ("Integers are fixed-point. Half-band taps divide by "
                    "2**(coeff_bits-1); modulator coefficients divide by "
                    "2**coeff_frac_bits.")
    (out / "coefficients.json").write_text(json.dumps(data, indent=2) + "\n")

    # SystemVerilog package. Constants rather than file reads, so synthesis
    # sees them directly.
    sv = ['// Generated by model/export_coefficients.py. Do not edit.',
          '//',
          '// Coefficients are signed fixed-point integers. A tap of width N',
          '// represents tap / 2**(N-1).',
          '',
          'package lyrebird_coeffs_pkg;',
          '',
          f'    localparam int SignalBits   = {SIGNAL_BITS};',
          f'    localparam int QuantBits    = {chain.QUANT_BITS};',
          f'    localparam int NumElements  = {chain.N_ELEMENTS};',
          f'    localparam int ModOrder     = {len(ntf.a)};',
          f'    localparam int ModCoeffBits = {MOD_BITS};',
          f'    localparam int ModCoeffFrac = {MOD_FRAC};',
          f'    localparam int ModStateInt  = 1;',
          "    localparam int ModStateBits [0:2] = '{28, 20, 20};",
          "    localparam int ModStateFrac [0:2] = '{26, 18, 18};",
          '']
    sv.append(f'    localparam logic signed [{MOD_BITS-1}:0] '
              f'ModA [0:{len(ntf.a)-1}] = \'{{')
    sv.append("        " + ", ".join(f"{MOD_BITS}'sd{v}" if v >= 0
                                     else f"-{MOD_BITS}'sd{abs(v)}"
                                     for v in data["modulator"]["a"]))
    sv.append("    };")
    sv.append("")
    for st in stages:
        n, b, i = st["n_taps"], st["coeff_bits"], st["index"]
        sv.append(f'    // stage {i}: {st["f_in_hz"]/1e3:g} -> '
                  f'{st["f_out_hz"]/1e3:g} kHz, {b}-bit, '
                  f'stopband {st["stopband_db"]:.1f} dB')
        sv.append(f'    localparam int Stage{i}Taps = {n};')
        sv.append(f'    localparam int Stage{i}Bits = {b};')
        sv.append(f'    localparam logic signed [{b-1}:0] '
                  f'Stage{i}Coeff [0:{n-1}] = \'{{')
        rows = []
        for k in range(0, n, 6):
            rows.append("        " + ", ".join(
                f"{b}'sd{v}" if v >= 0 else f"-{b}'sd{abs(v)}"
                for v in st["taps"][k:k + 6]))
        sv.append(",\n".join(rows))
        sv.append("    };")
        sv.append("")
    sv.append("endpackage")
    (ROOT / "hdl" / "rtl" / "lyrebird_coeffs_pkg.sv").write_text(
        "\n".join(sv) + "\n")

    # $readmemh files, two's complement at the stage width, for testbenches.
    hexdir = ROOT / "hdl" / "sim" / "coeffs"
    hexdir.mkdir(parents=True, exist_ok=True)
    for st in stages:
        b = st["coeff_bits"]
        digits = (b + 3) // 4
        lines = [format(v & ((1 << b) - 1), f"0{digits}x") for v in st["taps"]]
        (hexdir / f"stage{st['index']}.hex").write_text("\n".join(lines) + "\n")

    print(f"  {len(stages)} stages, modulator order {len(ntf.a)}")
    print(f"  {out / 'coefficients.json'}")
    print(f"  {ROOT / 'hdl/rtl/lyrebird_coeffs_pkg.sv'}")
    print(f"  {hexdir}/stage*.hex")
    return 0


if __name__ == "__main__":
    sys.exit(main())
