// Generated by model/export_coefficients.py. Do not edit.
//
// Coefficients are signed fixed-point integers. A tap of width N
// represents tap / 2**(N-1).

package lyrebird_coeffs_pkg;

    localparam int SignalBits   = 28;
    localparam int QuantBits    = 3;
    localparam int NumElements  = 7;
    localparam int ModOrder     = 3;
    localparam int ModCoeffBits = 24;
    localparam int ModCoeffFrac = 22;
    localparam int ModStateInt  = 1;
    localparam int ModStateBits [0:2] = '{28, 20, 20};
    localparam int ModStateFrac [0:2] = '{26, 18, 18};

    localparam logic signed [23:0] ModA [0:2] = '{
        24'sd739297, 24'sd3202025, 24'sd5610492
    };

    // stage 1: 48 -> 96 kHz, 26-bit, stopband -120.1 dB
    localparam int Stage1Taps = 163;
    localparam int Stage1Bits = 26;
    localparam logic signed [25:0] Stage1Coeff [0:162] = '{
        26'sd36, 26'sd0, -26'sd74, 26'sd0, 26'sd147, 26'sd0,
        -26'sd265, 26'sd0, 26'sd447, 26'sd0, -26'sd718, 26'sd0,
        26'sd1108, 26'sd0, -26'sd1655, 26'sd0, 26'sd2405, 26'sd0,
        -26'sd3414, 26'sd0, 26'sd4746, 26'sd0, -26'sd6479, 26'sd0,
        26'sd8701, 26'sd0, -26'sd11514, 26'sd0, 26'sd15033, 26'sd0,
        -26'sd19389, 26'sd0, 26'sd24728, 26'sd0, -26'sd31213, 26'sd0,
        26'sd39027, 26'sd0, -26'sd48372, 26'sd0, 26'sd59475, 26'sd0,
        -26'sd72590, 26'sd0, 26'sd88004, 26'sd0, -26'sd106046, 26'sd0,
        26'sd127098, 26'sd0, -26'sd151613, 26'sd0, 26'sd180140, 26'sd0,
        -26'sd213360, 26'sd0, 26'sd252147, 26'sd0, -26'sd297652, 26'sd0,
        26'sd351441, 26'sd0, -26'sd415727, 26'sd0, 26'sd493755, 26'sd0,
        -26'sd590503, 26'sd0, 26'sd714035, 26'sd0, -26'sd878313, 26'sd0,
        26'sd1109784, 26'sd0, -26'sd1465230, 26'sd0, 26'sd2092472, 26'sd0,
        -26'sd3533875, 26'sd0, 26'sd10671894, 26'sd16777216, 26'sd10671894, 26'sd0,
        -26'sd3533875, 26'sd0, 26'sd2092472, 26'sd0, -26'sd1465230, 26'sd0,
        26'sd1109784, 26'sd0, -26'sd878313, 26'sd0, 26'sd714035, 26'sd0,
        -26'sd590503, 26'sd0, 26'sd493755, 26'sd0, -26'sd415727, 26'sd0,
        26'sd351441, 26'sd0, -26'sd297652, 26'sd0, 26'sd252147, 26'sd0,
        -26'sd213360, 26'sd0, 26'sd180140, 26'sd0, -26'sd151613, 26'sd0,
        26'sd127098, 26'sd0, -26'sd106046, 26'sd0, 26'sd88004, 26'sd0,
        -26'sd72590, 26'sd0, 26'sd59475, 26'sd0, -26'sd48372, 26'sd0,
        26'sd39027, 26'sd0, -26'sd31213, 26'sd0, 26'sd24728, 26'sd0,
        -26'sd19389, 26'sd0, 26'sd15033, 26'sd0, -26'sd11514, 26'sd0,
        26'sd8701, 26'sd0, -26'sd6479, 26'sd0, 26'sd4746, 26'sd0,
        -26'sd3414, 26'sd0, 26'sd2405, 26'sd0, -26'sd1655, 26'sd0,
        26'sd1108, 26'sd0, -26'sd718, 26'sd0, 26'sd447, 26'sd0,
        -26'sd265, 26'sd0, 26'sd147, 26'sd0, -26'sd74, 26'sd0,
        26'sd36
    };

    // stage 4: 384 -> 768 kHz, 22-bit, stopband -120.4 dB
    localparam int Stage4Taps = 27;
    localparam int Stage4Bits = 22;
    localparam logic signed [21:0] Stage4Coeff [0:26] = '{
        22'sd157, 22'sd0, -22'sd1450, 22'sd0, 22'sd7095, 22'sd0,
        -22'sd24435, 22'sd0, 22'sd67934, 22'sd0, -22'sd175200, 22'sd0,
        22'sd650188, 22'sd1048576, 22'sd650188, 22'sd0, -22'sd175200, 22'sd0,
        22'sd67934, 22'sd0, -22'sd24435, 22'sd0, 22'sd7095, 22'sd0,
        -22'sd1450, 22'sd0, 22'sd157
    };

    // stage 5: 768 -> 1536 kHz, 19-bit, stopband -120.2 dB
    localparam int Stage5Taps = 15;
    localparam int Stage5Bits = 19;
    localparam logic signed [18:0] Stage5Coeff [0:14] = '{
        -19'sd400, 19'sd0, 19'sd3511, 19'sd0, -19'sd16327, 19'sd0,
        19'sd78752, 19'sd131072, 19'sd78752, 19'sd0, -19'sd16327, 19'sd0,
        19'sd3511, 19'sd0, -19'sd400
    };

    // stage 6: 1536 -> 3072 kHz, 18-bit, stopband -123.0 dB
    localparam int Stage6Taps = 11;
    localparam int Stage6Bits = 18;
    localparam logic signed [17:0] Stage6Coeff [0:10] = '{
        18'sd799, 18'sd0, -18'sd6492, 18'sd0, 18'sd38461, 18'sd65536,
        18'sd38461, 18'sd0, -18'sd6492, 18'sd0, 18'sd799
    };

    // stage 7: 3072 -> 6144 kHz, 10-bit, stopband -142.2 dB
    localparam int Stage7Taps = 11;
    localparam int Stage7Bits = 10;
    localparam logic signed [9:0] Stage7Coeff [0:10] = '{
        10'sd3, 10'sd0, -10'sd25, 10'sd0, 10'sd150, 10'sd256,
        10'sd150, 10'sd0, -10'sd25, 10'sd0, 10'sd3
    };

    // stage 8: 6144 -> 12288 kHz, 8-bit, stopband -122.7 dB
    localparam int Stage8Taps = 7;
    localparam int Stage8Bits = 8;
    localparam logic signed [7:0] Stage8Coeff [0:6] = '{
        -8'sd4, 8'sd0, 8'sd36, 8'sd64, 8'sd36, 8'sd0,
        -8'sd4
    };

    // stage 9: 12288 -> 24576 kHz, 8-bit, stopband -146.8 dB
    localparam int Stage9Taps = 7;
    localparam int Stage9Bits = 8;
    localparam logic signed [7:0] Stage9Coeff [0:6] = '{
        -8'sd4, 8'sd0, 8'sd36, 8'sd64, 8'sd36, 8'sd0,
        -8'sd4
    };

endpackage
